//go:build arm64 && !purego

// Code generated by wasm2go (gcasm backend). DO NOT EDIT.
//
// Import calls live in assembly, invisible to the linker's
// method pruning, which would fill every itab slot with
// runtime.unreachableMethod. init() is always reachable, so
// the never-taken calls below emit genuine interface call
// sites that pin each method. gcasmKeepAlive is never set.

package base

var gcasmKeepAlive bool

func init() {
	if !gcasmKeepAlive {
		return
	}
	(EnvImports)(nil).Dlerror(nil)
	(EnvImports)(nil).Dlopen(nil, 0, 0)
	(EnvImports)(nil).Dlsym(nil, 0, 0)
	(EnvImports)(nil).Getpid(nil)
	(Wasi_snapshot_preview1Imports)(nil).Clock_res_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Clock_time_get(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Environ_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Environ_sizes_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_advise(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_close(nil, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_datasync(nil, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_fdstat_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_fdstat_set_flags(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_filestat_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_filestat_set_size(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_filestat_set_times(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_pread(nil, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_prestat_dir_name(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_prestat_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_pwrite(nil, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_read(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_readdir(nil, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_seek(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_sync(nil, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_tell(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_write(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_create_directory(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_filestat_get(nil, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_filestat_set_times(nil, 0, 0, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_link(nil, 0, 0, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_open(nil, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_readlink(nil, 0, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_remove_directory(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_rename(nil, 0, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_symlink(nil, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_unlink_file(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Pipe(nil, 0)
	(Wasi_snapshot_preview1Imports)(nil).Poll_oneoff(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Proc_exit(nil, 0)
	(Wasi_snapshot_preview1Imports)(nil).Proc_spawn(nil, 0, 0, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Proc_wait(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Random_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Sched_yield(nil)
	(Wasi_snapshot_preview1Imports)(nil).Sock_accept(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Sock_connect(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Sock_getaddrinfo(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Sock_recv(nil, 0, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Sock_send(nil, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Sock_shutdown(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Sock_socket(nil, 0, 0)
}
